In [3]:
import numpy as np
raster = np.array([[4,1],[2,2]])
raster

array([[4, 1],
       [2, 2]])

In [4]:
numpoints = np.sum(raster)
points = np.zeros((numpoints,2), dtype=int)
points

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

"Vanilla Python" with for loops

In [5]:
point = 0
for r in range(0, raster.shape[0]):
    for c in range(0, raster.shape[1]):
        # create n points for number n in the raster cell:
        for n in range(0, raster[r,c]):
            points[point,0] = r
            points[point,1] = c
            point = point + 1
            
points

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 1],
       [1, 1]])

Using numpy's [nditer](https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.nditer.html#tracking-an-index-or-multi-index) and [append](https://docs.scipy.org/doc/numpy/reference/generated/numpy.append.html):

In [57]:
# make an empty 2D "target array"
points2 = np.zeros((numpoints,2), dtype=int)

# keep track of where in the target array we have to insert
insertrow = 0

# iterate over the input raster
it = np.nditer(raster, flags=['multi_index'])
while not it.finished:
    entry = np.array([np.array(it.multi_index)])
    block = np.repeat(entry, it[0], axis=0)
    points2[insertrow:insertrow+block.shape[0]] = block
    insertrow = insertrow + block.shape[0]
    it.iternext()
    
print(points2)

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 0]
 [1 0]
 [1 1]
 [1 1]]


In [58]:
np.array_equal(points, points2)

True